nav:
  - 主页: index.md
  - 账号:
    - 账号申请: accounts/apply.md
    - 密码: accounts/passwords.md
  #   - 账号管理: accounts/management.md
  #   - 机时充值: accounts/charge.md
  #   - 收费细则: accounts/fee.md
  - 登陆: 
    - SSH: login/SSH.md
    - 登陆节点: login/login.md
    - Tmux: login/tmux.md
  # - 文件系统:
  #   - 概览: 文件系统/概览.md
  #   - 数据传输: 文件系统/数据传输.md
  #   - 与校云计算文件交互: 文件系统/云平台.md
  #   - 与其他用户共享文件: 文件系统/共享文件.md 
  - 可视化平台:
    - 基础操作: studio/basic.md
    - 远程桌面: studio/remote-desktop.md
    - Jupyter: studio/jupyter.md
    - RStudio: studio/rstudio.md
  - 提交作业:
    - Slurm概览: job/slurm.md
    # - 脚本式作业: 作业/脚本式作业.md
    # - MPI、OpenMP、CUDA作业示例: 作业/MPI、OpenMP、CUDA作业示例.md
    - 作业示例: job/jobsamples_basic.md
    - 作业示例（开发者）: job/jobsamples.md
    # - 交互式作业: 作业/交互式作业.md
    # - 队列选择: 作业/队列选择.md
    - DGX2: job/dgx.md
    - 节点预约: job/reservation.md
    # - 作业优先级: 作业/作业优先级.md
    - 容器: job/container/singularity.md
    - 非特权容器构建: job/container/u2cb.md
  - 应用软件:
    - Pi 上的软件: application/applications.md
    - 用 Conda 安装生信软件: application/conda.md
    - 预置软件环境: application/module.md
    - ABINIT: application/abinit.md
    - Amber: application/Amber.md
    - CESM: application/CESM.md
    - Gromacs: application/Gromacs.md
    - Lammps: application/Lammps.md
    - Mrbayes: application/mrbayes.md
    - Nektar++: application/Nektar.md
    - NWChem: application/nwchem.md
    - OpenFoam: application/OpenFoam.md
    - Pytorch: application/Pytorch.md
    - Quantum-Espresso: application/Quantum-Espresso.md
    - Relion: application/Relion.md
    - STAR-CCM+: application/star-ccm.md
    - TensorFlow: application/TensorFlow.md
    - VASP: application/VASP.md
    - VMD: application/VMD.md    
    - Keras: application/Keras.md
    - SIESTA: application/SIESTA.md
    - CP2k: application/CP2k.md
  #   - Desmond and Maestro: 应用软件/Desmond_and_Maestro.md  
  #   - FFTW: 应用软件/FFTW.md
  #   - MPI4PY: 应用软件/MPI4PY.md
  #   - MXNet: 应用软件/MXNet.md
  #   - HIC-Pro: 应用软件/HIC-Pro.md
  #   - Spark: 应用软件/Spark.md
  #  - 商业软件: application/commercial.md
  - 编程语言:
    - Python: application/Python.md
    - Perl: application/Perl.md
    - R: application/R.md
    - Octave(Matlab): application/Octave.md
    - GNU Library: application/GNU.md
    - Intel编译套件: application/Intel.md
    - CUDA: application/cuda.md
  - 常见问题: faq.md
  #- 提交修改: contribution.md

# Project Information
site_name: Pi Documentation
site_description: Pi Documentation
site_author: SJTU HPC Team
site_dir: public
site_url: "https://docs.hpc.sjtu.edu.cn"
repo_name: SJTU-HPC/docs.hpc.sjtu.edu.cn
repo_url: https://github.com/SJTU-HPC/docs.hpc.sjtu.edu.cn
edit_uri: tree/master/docs/

# Configuration
strict: false

theme:
  name: material
  custom_dir: material
  favicon: img/favicon.png
  palette:
    primary: mute-turquoise
    accent: orange
  logo: img/logos.png

# Extensions
markdown_extensions:
  - meta
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - minify:
      minify_html: true

